"""add email templates and emails

Revision ID: 3cd2e75fd3b4
Revises: 69df4e22cd3f
Create Date: 2026-03-09 12:32:02.024374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd2e75fd3b4'
down_revision: Union[str, Sequence[str], None] = '69df4e22cd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_template'))
    )
    with op.batch_alter_table('email_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_template_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_template_name'), ['name'], unique=True)

    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['email_template.id'], name=op.f('fk_email_template_id_email_template')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_email_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email'))
    )
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_status'), ['status'], unique=False)
        batch_op.create_index('ix_email_template_id_ref', ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_to_email'), ['to_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_user_id'), ['user_id'], unique=False)

    op.create_table('email_template_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['email_template.id'], name=op.f('fk_email_template_translation_template_id_email_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_template_translation')),
    sa.UniqueConstraint('template_id', 'locale', name='uq_email_template_translation_template_locale')
    )
    with op.batch_alter_table('email_template_translation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_template_translation_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_template_translation_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_template_translation_template_id'), ['template_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_template_translation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_template_translation_template_id'))
        batch_op.drop_index(batch_op.f('ix_email_template_translation_locale'))
        batch_op.drop_index(batch_op.f('ix_email_template_translation_id'))

    op.drop_table('email_template_translation')
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_to_email'))
        batch_op.drop_index('ix_email_template_id_ref')
        batch_op.drop_index(batch_op.f('ix_email_status'))
        batch_op.drop_index(batch_op.f('ix_email_id'))

    op.drop_table('email')
    with op.batch_alter_table('email_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_template_name'))
        batch_op.drop_index(batch_op.f('ix_email_template_id'))

    op.drop_table('email_template')
    # ### end Alembic commands ###
