"""Add category and product models

Revision ID: 6032a2899f4c
Revises: c18daec42678
Create Date: 2026-03-08 13:02:15.262456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6032a2899f4c'
down_revision: Union[str, Sequence[str], None] = 'c18daec42678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_default_ship_address_id_address'), 'address', ['default_ship_address_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_default_bill_address_id_address'), 'address', ['default_bill_address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_default_bill_address_id_address'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_default_ship_address_id_address'), type_='foreignkey')

    # ### end Alembic commands ###
