"""remove company from address

Revision ID: 69df4e22cd3f
Revises: 43b3129ccdb1
Create Date: 2026-03-09 07:14:52.040533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69df4e22cd3f'
down_revision: Union[str, Sequence[str], None] = '43b3129ccdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
