"""add_country_and_province_state_tables

Revision ID: 8870e3a6f2e6
Revises: 79b848aaf126
Create Date: 2026-03-08 04:19:02.882850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8870e3a6f2e6'
down_revision: Union[str, Sequence[str], None] = '79b848aaf126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_index(op.f('ix_country_iso_code'), 'country', ['iso_code'], unique=True)
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=True)
    op.create_table('provincestate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provincestate_code'), 'provincestate', ['code'], unique=False)
    op.create_index(op.f('ix_provincestate_id'), 'provincestate', ['id'], unique=False)
    op.create_index(op.f('ix_provincestate_name'), 'provincestate', ['name'], unique=False)
    # --- Seed Data ---
    # Countries
    op.execute(
        "INSERT INTO country (id, name, iso_code, is_active) VALUES "
        "(1, 'United States', 'US', 1), "
        "(2, 'Canada', 'CA', 1)"
    )

    # US States
    op.execute(
        "INSERT INTO provincestate (name, code, country_id, is_active) VALUES "
        "('Alabama', 'AL', 1, 1), "
        "('Alaska', 'AK', 1, 1), "
        "('Arizona', 'AZ', 1, 1), "
        "('Arkansas', 'AR', 1, 1), "
        "('California', 'CA', 1, 1), "
        "('Colorado', 'CO', 1, 1), "
        "('Connecticut', 'CT', 1, 1), "
        "('Delaware', 'DE', 1, 1), "
        "('District of Columbia', 'DC', 1, 1), "
        "('Florida', 'FL', 1, 1), "
        "('Georgia', 'GA', 1, 1), "
        "('Hawaii', 'HI', 1, 1), "
        "('Idaho', 'ID', 1, 1), "
        "('Illinois', 'IL', 1, 1), "
        "('Indiana', 'IN', 1, 1), "
        "('Iowa', 'IA', 1, 1), "
        "('Kansas', 'KS', 1, 1), "
        "('Kentucky', 'KY', 1, 1), "
        "('Louisiana', 'LA', 1, 1), "
        "('Maine', 'ME', 1, 1), "
        "('Maryland', 'MD', 1, 1), "
        "('Massachusetts', 'MA', 1, 1), "
        "('Michigan', 'MI', 1, 1), "
        "('Minnesota', 'MN', 1, 1), "
        "('Mississippi', 'MS', 1, 1), "
        "('Missouri', 'MO', 1, 1), "
        "('Montana', 'MT', 1, 1), "
        "('Nebraska', 'NE', 1, 1), "
        "('Nevada', 'NV', 1, 1), "
        "('New Hampshire', 'NH', 1, 1), "
        "('New Jersey', 'NJ', 1, 1), "
        "('New Mexico', 'NM', 1, 1), "
        "('New York', 'NY', 1, 1), "
        "('North Carolina', 'NC', 1, 1), "
        "('North Dakota', 'ND', 1, 1), "
        "('Ohio', 'OH', 1, 1), "
        "('Oklahoma', 'OK', 1, 1), "
        "('Oregon', 'OR', 1, 1), "
        "('Pennsylvania', 'PA', 1, 1), "
        "('Rhode Island', 'RI', 1, 1), "
        "('South Carolina', 'SC', 1, 1), "
        "('South Dakota', 'SD', 1, 1), "
        "('Tennessee', 'TN', 1, 1), "
        "('Texas', 'TX', 1, 1), "
        "('Utah', 'UT', 1, 1), "
        "('Vermont', 'VT', 1, 1), "
        "('Virginia', 'VA', 1, 1), "
        "('Washington', 'WA', 1, 1), "
        "('West Virginia', 'WV', 1, 1), "
        "('Wisconsin', 'WI', 1, 1), "
        "('Wyoming', 'WY', 1, 1)"
    )

    # Canadian Provinces and Territories
    op.execute(
        "INSERT INTO provincestate (name, code, country_id, is_active) VALUES "
        "('Alberta', 'AB', 2, 1), "
        "('British Columbia', 'BC', 2, 1), "
        "('Manitoba', 'MB', 2, 1), "
        "('New Brunswick', 'NB', 2, 1), "
        "('Newfoundland and Labrador', 'NL', 2, 1), "
        "('Northwest Territories', 'NT', 2, 1), "
        "('Nova Scotia', 'NS', 2, 1), "
        "('Nunavut', 'NU', 2, 1), "
        "('Ontario', 'ON', 2, 1), "
        "('Prince Edward Island', 'PE', 2, 1), "
        "('Quebec', 'QC', 2, 1), "
        "('Saskatchewan', 'SK', 2, 1), "
        "('Yukon', 'YT', 2, 1)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provincestate_name'), table_name='provincestate')
    op.drop_index(op.f('ix_provincestate_id'), table_name='provincestate')
    op.drop_index(op.f('ix_provincestate_code'), table_name='provincestate')
    op.drop_table('provincestate')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_index(op.f('ix_country_iso_code'), table_name='country')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
