"""add_merchant_store_storetranslation

Revision ID: c18daec42678
Revises: cc0e75521e2b
Create Date: 2026-03-08 06:24:12.240990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18daec42678'
down_revision: Union[str, Sequence[str], None] = 'cc0e75521e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('billing_address_id', sa.Integer(), nullable=True),
    sa.Column('shipping_address_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['billing_address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_company_name'), 'merchant', ['company_name'], unique=False)
    op.create_index(op.f('ix_merchant_id'), 'merchant', ['id'], unique=False)
    op.create_index(op.f('ix_merchant_user_id'), 'merchant', ['user_id'], unique=True)
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('brand_tagline', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_id'), 'store', ['id'], unique=False)
    op.create_index(op.f('ix_store_merchant_id'), 'store', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_store_slug'), 'store', ['slug'], unique=True)
    op.create_table('storetranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('brand_tagline', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'locale', name='uq_storetranslation_store_locale')
    )
    op.create_index(op.f('ix_storetranslation_id'), 'storetranslation', ['id'], unique=False)
    op.create_index(op.f('ix_storetranslation_locale'), 'storetranslation', ['locale'], unique=False)
    op.create_index(op.f('ix_storetranslation_store_id'), 'storetranslation', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storetranslation_store_id'), table_name='storetranslation')
    op.drop_index(op.f('ix_storetranslation_locale'), table_name='storetranslation')
    op.drop_index(op.f('ix_storetranslation_id'), table_name='storetranslation')
    op.drop_table('storetranslation')
    op.drop_index(op.f('ix_store_slug'), table_name='store')
    op.drop_index(op.f('ix_store_merchant_id'), table_name='store')
    op.drop_index(op.f('ix_store_id'), table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('ix_merchant_user_id'), table_name='merchant')
    op.drop_index(op.f('ix_merchant_id'), table_name='merchant')
    op.drop_index(op.f('ix_merchant_company_name'), table_name='merchant')
    op.drop_table('merchant')
    # ### end Alembic commands ###
