"""add_permissions_and_access_groups

Revision ID: cc0e75521e2b
Revises: 3e5ce6be5337
Create Date: 2026-03-08 05:08:56.345043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0e75521e2b'
down_revision: Union[str, Sequence[str], None] = '3e5ce6be5337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessgroup_id'), 'accessgroup', ['id'], unique=False)
    op.create_index(op.f('ix_accessgroup_name'), 'accessgroup', ['name'], unique=True)
    op.create_table('permissiondisplaygroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissiondisplaygroup_id'), 'permissiondisplaygroup', ['id'], unique=False)
    op.create_index(op.f('ix_permissiondisplaygroup_name'), 'permissiondisplaygroup', ['name'], unique=True)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('display_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['display_group_id'], ['permissiondisplaygroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_index(op.f('ix_permission_permission'), 'permission', ['permission'], unique=True)
    op.create_table('roleaccessgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('access_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_group_id'], ['accessgroup.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'access_group_id', name='uq_role_accessgroup')
    )
    op.create_index(op.f('ix_roleaccessgroup_id'), 'roleaccessgroup', ['id'], unique=False)
    op.create_table('accessgrouppermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_group_id'], ['accessgroup.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_group_id', 'permission_id', name='uq_accessgroup_permission')
    )
    op.create_index(op.f('ix_accessgrouppermission_id'), 'accessgrouppermission', ['id'], unique=False)
    # ### end Alembic commands ###

    # --- Seed: Add Merchant role ---
    op.execute("INSERT INTO role (id, name) VALUES (3, 'Merchant')")

    # --- Seed: PermissionDisplayGroups ---
    # id: 1=Product, 2=User, 3=Order, 4=Cart
    op.execute(
        "INSERT INTO permissiondisplaygroup (id, name) VALUES "
        "(1, 'Product'), "
        "(2, 'User'), "
        "(3, 'Order'), "
        "(4, 'Cart')"
    )

    # --- Seed: Permissions (attribute-based) ---
    # Product permissions (display_group_id=1): ids 1-4
    # User permissions    (display_group_id=2): ids 5-8
    # Order permissions   (display_group_id=3): ids 9-12
    # Cart permissions    (display_group_id=4): ids 13-16
    op.execute(
        "INSERT INTO permission (id, permission, display_group_id) VALUES "
        # Product
        "(1,  'product:create', 1), "
        "(2,  'product:read',   1), "
        "(3,  'product:update', 1), "
        "(4,  'product:delete', 1), "
        # User
        "(5,  'user:create', 2), "
        "(6,  'user:read',   2), "
        "(7,  'user:update', 2), "
        "(8,  'user:delete', 2), "
        # Order
        "(9,  'order:create', 3), "
        "(10, 'order:read',   3), "
        "(11, 'order:update', 3), "
        "(12, 'order:delete', 3), "
        # Cart
        "(13, 'cart:create', 4), "
        "(14, 'cart:read',   4), "
        "(15, 'cart:update', 4), "
        "(16, 'cart:delete', 4)"
    )

    # --- Seed: AccessGroups ---
    # id: 1=Admin, 2=Shopper, 3=Merchant
    op.execute(
        "INSERT INTO accessgroup (id, name) VALUES "
        "(1, 'Admin'), "
        "(2, 'Shopper'), "
        "(3, 'Merchant')"
    )

    # --- Seed: AccessGroupPermissions ---
    # Admin (id=1) → all 16 permissions
    # Shopper (id=2) → product:read, cart:*, order:create, order:read
    # Merchant (id=3) → product:*, order:read, order:update

    # Admin: all permissions
    admin_perms = ", ".join(
        f"({i + 1}, 1, {perm_id})" for i, perm_id in enumerate(range(1, 17))
    )
    op.execute(f"INSERT INTO accessgrouppermission (id, access_group_id, permission_id) VALUES {admin_perms}")

    # Shopper: product:read(2), cart:create(13), cart:read(14), cart:update(15), cart:delete(16),
    #          order:create(9), order:read(10)
    shopper_perm_ids = [2, 9, 10, 13, 14, 15, 16]
    shopper_rows = ", ".join(
        f"({17 + i}, 2, {pid})" for i, pid in enumerate(shopper_perm_ids)
    )
    op.execute(f"INSERT INTO accessgrouppermission (id, access_group_id, permission_id) VALUES {shopper_rows}")

    # Merchant: product:create(1), product:read(2), product:update(3), product:delete(4),
    #           order:read(10), order:update(11)
    merchant_perm_ids = [1, 2, 3, 4, 10, 11]
    merchant_rows = ", ".join(
        f"({24 + i}, 3, {pid})" for i, pid in enumerate(merchant_perm_ids)
    )
    op.execute(f"INSERT INTO accessgrouppermission (id, access_group_id, permission_id) VALUES {merchant_rows}")

    # --- Seed: RoleAccessGroups ---
    # Role: Shopper(1) → AccessGroup: Shopper(2)
    # Role: Admin(2)   → AccessGroup: Admin(1)
    # Role: Merchant(3)→ AccessGroup: Merchant(3)
    op.execute(
        "INSERT INTO roleaccessgroup (id, role_id, access_group_id) VALUES "
        "(1, 1, 2), "
        "(2, 2, 1), "
        "(3, 3, 3)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accessgrouppermission_id'), table_name='accessgrouppermission')
    op.drop_table('accessgrouppermission')
    op.drop_index(op.f('ix_roleaccessgroup_id'), table_name='roleaccessgroup')
    op.drop_table('roleaccessgroup')
    op.drop_index(op.f('ix_permission_permission'), table_name='permission')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_permissiondisplaygroup_name'), table_name='permissiondisplaygroup')
    op.drop_index(op.f('ix_permissiondisplaygroup_id'), table_name='permissiondisplaygroup')
    op.drop_table('permissiondisplaygroup')
    op.drop_index(op.f('ix_accessgroup_name'), table_name='accessgroup')
    op.drop_index(op.f('ix_accessgroup_id'), table_name='accessgroup')
    op.drop_table('accessgroup')
    # ### end Alembic commands ###
